### ISSUE TITLE
"zero dependency"

### ISSUE THREAD

**Issue by 3052** [zengxs/python-gpapi2#1]
this is pretty misleading:
https://github.com/zengxs/python-gpapi2/blob/73ea85c8550106863f521e33e5a909f0060bc0ce/README.md?plain=1#L15

as Rust is required:

~~~
> pip install https://github.com/zengxs/python-gpapi2/archive/refs/heads/main.zip
Collecting https://github.com/zengxs/python-gpapi2/archive/refs/heads/main.zip
  Downloading https://github.com/zengxs/python-gpapi2/archive/refs/heads/main.zip
     - 29.3 kB 1.6 MB/s 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
~~~

**Comment by 3052** [comment]
https://github.com/NoMore201/googleplay-api/issues/179

**Comment by zengxs** [comment]
You only need to install this library from PyPI:

```sh
pip install python-gpapi2
```

With this simple pip command, you don't need to download any additional libraries or perform any compilation steps.

There are precompiled wheel packages available for all major systems, including macOS x86-64/arm64, Windows x86-64/x86, Linux x86-64/x86/arm64 for both glibc and musl).

If the system you need is not among the mainstream platforms, you can let me know, and I can try to add a precompiled package for that platform.

**Comment by 3052** [comment]
OK, but what if you make a new commit, and we want the current version?

**Comment by zengxs** [comment]
@3052 Of course, you can always get the current version from a specific commit. In fact, GitHub Actions builds a wheel package for every commit in this project. If you need to install a precompiled wheel for a specific commit, you can follow these steps:

1. Navigate to the GitHub Actions page for the specific commit you are interested in.
2. Find the workflow run corresponding to that commit.
3. Download the artifact for your platform from the workflow run.
4. Extract the artifact, which will contain the precompiled wheel package.
5. Install the wheel package using pip:

```bash
pip install /path/to/downloaded/wheel.whl
```

This way, you can ensure you are using the exact version you need without requiring Rust or any additional compilation steps.

**Comment by 3052** [comment]
your logic is flawed. the key question here is this: who is the audience for the phrase "zero dependency"?

the "consumers" of this project are not the audience. as you said, they can download releases already built, and even every commit already built, so telling those users "zero dependency" is completely pointless, because even if project has 100 dependency, they never know because its built.

the real audience for this phrase is DEVELOPERS. people who will take the code, change it, improve it, and run it. for THAT audience, YES this project has a dependency, a BIG one Rust. so again, the phrase "zero dependency" is just objectively wrong here, regardless of any rationalizations you have.

**Comment by zengxs** [comment]
Thank you for your input. However, I believe this discussion is no longer productive and is leading to unnecessary confusion. Therefore, I have decided to close this issue.
